[package]
name = "data_patcher"
version = "0.1.0"

authors.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
